'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderConfirmation

    '''<summary>
    '''lblOrderId control.
    '''</summary>
    Protected WithEvents lblOrderId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransactionNumber control.
    '''</summary>
    Protected WithEvents lblTransactionNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrderDate control.
    '''</summary>
    Protected WithEvents lblOrderDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymentType control.
    '''</summary>
    Protected WithEvents lblPaymentType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalAmount control.
    '''</summary>
    Protected WithEvents lblTotalAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrderStatus control.
    '''</summary>
    Protected WithEvents lblOrderStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptReceiptItems control.
    '''</summary>
    Protected WithEvents rptReceiptItems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlPendingMessage control.
    '''</summary>
    Protected WithEvents pnlPendingMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnTrackOrder control.
    '''</summary>
    Protected WithEvents btnTrackOrder As Global.System.Web.UI.WebControls.Button
End Class
