'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm11

    '''<summary>
    '''litPendingOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPendingOrders As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompletedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompletedOrders As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCancelledOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCancelledOrders As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTotalOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTotalOrders As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents ddlFilterStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlQuickDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlNoOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoOrders As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOrders As Global.System.Web.UI.WebControls.Repeater

    Protected WithEvents rptMasterOrders As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlDetailView As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlNoSelectedOrder As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litDetailOrderId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailOrderDate As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailStatusBadge As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailCustAvatar As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailCustName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailCustPhone As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lnkCallCust As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents litDetailAddress As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailPayment As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents rptDetailItems As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents litDetailSubtotal As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailTax As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailGrandTotal As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlAcceptAction As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnDetailAccept As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlDispatchAction As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlDetailDriver As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnDetailDispatch As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlDispatchedDriverBadge As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litDetailDriverName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailDriverPhone As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lnkCallDriver As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents litDetailDriverVehicle As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDetailOtp As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnDetailComplete As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlCompletedAction As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litDetailDeliveredTime As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents btnDetailCancel As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnDetailPrint As Global.System.Web.UI.WebControls.Button

    Protected WithEvents rptPending As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptPreparing As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptDispatched As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptCompleted As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents litPendingCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litPreparingCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDispatchedCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litCompletedCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnkFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFirst As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPrevious As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptPagination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPagination As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lnkNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNext As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLast As Global.System.Web.UI.WebControls.LinkButton
End Class
