'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ManageDrivers

    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    Protected WithEvents updDrivers As Global.System.Web.UI.UpdatePanel
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalDrivers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblAvailableDrivers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblOnDeliveryDrivers As Global.System.Web.UI.WebControls.Label
    Protected WithEvents litFormTitle As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents hfDriverId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtDriverName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvDriverName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents revPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtVehicleNo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvVehicleNo As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents btnSaveDriver As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelDriver As Global.System.Web.UI.WebControls.Button
    Protected WithEvents ddlStatusFilter As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtSearchDriver As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rptDrivers As Global.System.Web.UI.WebControls.Repeater

End Class
