'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Public Partial Class ManageInventory

    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    Protected WithEvents updInventory As Global.System.Web.UI.UpdatePanel

    Protected WithEvents lblTotalItems As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblHealthyItems As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblLowStockCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalValuation As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlRecipeFinancials As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDishSellingPrice As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblEstRecipeCost As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblEstGrossMargin As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnTabIngredients As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnTabRecipe As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlIngredients As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litFormTitle As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents hfIngredientId As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents txtIngredientName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtStockQty As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlUnit As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtCostPerUnit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtLowStockThreshold As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSaveIngredient As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelIngredient As Global.System.Web.UI.WebControls.Button
    Protected WithEvents ddlStockFilter As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtSearchIngredient As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rptIngredients As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoIngredients As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlRecipe As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlRecipeDish As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlRecipeIngredient As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtRecipeQty As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnAddRecipeItem As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rfvIngredientName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rfvStockQty As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cvStockQty As Global.System.Web.UI.WebControls.CompareValidator
    Protected WithEvents rfvCostPerUnit As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cvCostPerUnit As Global.System.Web.UI.WebControls.CompareValidator
    Protected WithEvents rfvThreshold As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cvThreshold As Global.System.Web.UI.WebControls.CompareValidator

    Protected WithEvents rfvRecipeDish As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rfvRecipeIngredient As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rfvRecipeQty As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cvRecipeQty As Global.System.Web.UI.WebControls.CompareValidator

    Protected WithEvents lblSelectedDishName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptRecipeItems As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoRecipeItems As Global.System.Web.UI.WebControls.Panel
End Class
