'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class DriverPortal

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    Protected WithEvents lblDriverName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblVehicleNo As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblDutyStatus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnToggleDuty As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents updDriverPortal As Global.System.Web.UI.UpdatePanel
    Protected WithEvents tmrAutoRefresh As Global.System.Web.UI.Timer
    Protected WithEvents lblDriverWelcomeName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblActiveCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblCompletedCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalCashCollected As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptActiveDeliveries As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoActive As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents ddlHistoryFilter As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtHistoryStart As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtHistoryEnd As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnFilterHistory As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptCompletedDeliveries As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoCompleted As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlExpressPopUp As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litExpressOrderId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litExpressCustName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litExpressAddress As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litExpressPayment As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litExpressTotal As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnExpressClaim As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblPoolBadge As Global.System.Web.UI.WebControls.Label
    Protected WithEvents rptAvailablePool As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoPool As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litNoPoolMsg As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnOpenChangePwd As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents pnlChangePasswordModal As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnClosePwdModal As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblPwdMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtCurrentPwd As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNewPwd As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtConfirmPwd As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnUpdatePassword As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancelPwd As Global.System.Web.UI.WebControls.Button

End Class
