'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class DriverLogin

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

End Class
